[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mypf"
version = "0.1"
authors = [
  { name="Drew Gochenaur" }
]
requires-python = ">=3.9"
dependencies = [
  "pyyaml"
]

[project.scripts]
pf-dump = "mypf.pf_dump:main"
